language: node_js
node_js: '12'
cache:
  yarn: true
  directories:
    - node_modules
    - '$HOME/.cache/electron'
    - '$HOME/.cache/electron-builder'
install:
  - yarn
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

stages:
  # - name: test
  - name: build
    if: tag IS present

jobs:
  include:
    # - stage: test	
    #   name: 'test'	
    #   os: linux	
    #   dist: xenial	
    #   script:	
    #     - yarn unit-test	
    #     - yarn int-test	
    #     - yarn build --linux --publish never
    - name: build_web	
      os: linux	
      script:	
        - yarn build --progress=false	
      deploy:	
        provider: netlify	
        site: $NETLIFY_SITE_ID	
        auth: $NETLIFY_AUTH_TOKEN	
        dir: 'dist/'	
        prod: true	
        message: 'Travis CI deployment'	
        edge: true	
        skip_cleanup: true
        on:
          tags: true
          branch: master
    - stage: build
      name: build_electron
      os: osx
      osx_image: xcode10.2
      script:
        - mkdir -p ~/$TRAVIS_BUILD_NUMBER/mac
        - yarn electron:build --publish never
      deploy:
      - provider: releases
        token: $GH_TOKEN
        file_glob: true
        file:
        - "electron/dist/COMPCON*.AppImage"
        - "electron/dist/COMPCON*.exe"
        - "electron/dist/COMPCON*mac.zip"
        on:
          tags: true
          branch: master
        edge: true
      - provider: script
        on:
          tags: true
          branch: master
        script: bash build_scripts/deploy_butler.sh
        edge: true