language: node_js
node_js: "10"
cache: yarn
install:
  - yarn
sudo: false

matrix:
  include:
  - name: osx_build
    os: osx
    osx_image: xcode10.2
    script: yarn dist -m
  - name: linux_build
    os: linux
    dist: xenial
    script: yarn dist -l
  - name: win_build
    os: osx
    osx_image: xcode10.2
    script: yarn dist -w

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  only:
    - stable
    - beta
    - tso_ci_pipeline
    