osx_image: xcode10.2

dist: xenial
sudo: false

language: node_js
node_js: "10"
cache: yarn

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx

install:
  - yarn

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn dist; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn dist --mac --win; fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  only:
    - stable
    - beta
    - tso_ci_pipeline
    