language: node_js
node_js: '10'
cache:
  yarn: true
  directories:
    - node_modules
    - '$HOME/.cache/electron'
    - '$HOME/.cache/electron-builder'
install:
  - yarn
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

stages:
  - name: build

jobs:
  include:
    - stage: build
      name: build_electron
      os: osx
      osx_image: xcode10.2
      script:
        - mkdir -p ~/$TRAVIS_BUILD_NUMBER/mac
        - yarn electron:build -mwl --publish never
      deploy:
      - provider: releases
        skip_cleanup: true
        api_key: $GH_TOKEN
        file_glob: true
        file:
        - "electron/dist/COMPCON*.AppImage"
        - "electron/dist/COMPCON*.exe"
        - "electron/dist/COMPCON*mac.zip"
        skip_cleanup: true
        draft: true
        on:
          branch: v2_electron
          tags: true
      - provider: script
        skip_cleanup: true
        on:
          branch: v2_electron
          tags: true
        script: bash build_scripts/deploy_butler.sh
